module-item-order-groupings = [
  ["use", ["use"]],
  ["modules", ["extern_crate", "mod", "foreign_mode"]],
  [
    "everything_else",
    [
      "macro",
      "global_asm",
      "static",
      "const",
      "ty_alias",
      "opaque_ty",
      "enum",
      "struct",
      "union",
      "trait",
      "trait_alias",
      "impl",
      "fn",
    ],
  ],
]
allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-panic-in-tests = true
allow-unwrap-in-tests = true
avoid-breaking-exported-api = false
suppress-restriction-lint-in-const = true
