absolute-paths-max-segments = 3
allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-mixed-uninlined-format-args = false
allow-panic-in-tests = true
allow-unwrap-in-consts = false
allow-unwrap-in-tests = true
avoid-breaking-exported-api = false
check-incompatible-msrv-in-tests = true
check-private-items = false
enforce-iter-loop-reborrow = true
enum-variant-name-threshold = 2
excessive-nesting-threshold = 6
inherent-impl-lint-scope = "file"
lint-commented-code = true
max-fn-params-bools = 1
missing-docs-allow-unused = true
suppress-restriction-lint-in-const = true
