author = "jezzy jumble"

[palette]
blackboard = "#181716"
soil = "#73665b"
strawberry = "#f56e7f"
salmon = "#f58669"
sour_apple = "#bec975"
leaf = "#97ca95"
honeycomb = "#e8d6a7"
creamsicle = "#f4b86a"
violet = "#caa2ca"
blueberry = "#9293ec"
cherry_blossom = "#e5a1a3"
princess = "#ef7dc0"
sky = "#a5b6ce"
bay = "#5dccc3"
elephant = "#88847f"
chalk = "#d5d0c9"
metal = "#242628"
film = "#2e2a27"
onyx = "#404040"
sea = "#164a4f"
lemon = "#ffef43"

[roles]
background = "blackboard"
foreground = "chalk"
color00 = "blackboard"
color01 = "strawberry"
color02 = "sour_apple"
color03 = "honeycomb"
color04 = "violet"
color05 = "cherry_blossom"
color06 = "sky"
color07 = "elephant"
color08 = "soil"
color09 = "salmon"
color10 = "leaf"
color11 = "creamsicle"
color12 = "blueberry"
color13 = "princess"
color14 = "bay"
color15 = "chalk"
