[meta]
author = "jezzy jumble (@jezzy-ultra)"
license = "MPL-2.0"
blurb = "cute af theme for queers ♡"

[palette]
blackboard = "#181716"
strawberry = "#f76f80"
sour_apple = "#bec975"
honeycomb = "#e8d6a7"
lilac = "#caa2ca"
cherry_blossom = "#e5a1a3"
sky = "#a5b6ce"
elephant = "#88847f"
soil = "#73665b"
sand = "#f98959"
goddess = "#a2caa0"
creamsicle = "#f7bb6c"
blueberry = "#9e9fec"
princess = "#fa7fb5"
peacock = "#8accc7"
chalk = "#d5d0c9"
peach = "#e4b99d"
coral = "#fa9485"
raven = "#0a0909"
ink = "#111010"
cocoa = "#1f1e1b"
date = "#210f11"
film = "#2e2a27"
charcoal = "#313735"
asphalt = "#433a31"
sea = "#0f3f4e"
opium = "#978182"
sage = "#878972"
cloud = "#808387"
orchid = "#ec89ed"
nectarine = "#f1d090"
salsa = "#f7524c"
lantern = "#f7bf32"
lemon = "#ffef43"

[slots]
bg = "$blackboard"
fg = "$chalk"
fg_alt = "$raven"
toolbar = "$film"
toolbar_popup = "$cocoa"
toolbar_alt = "$raven"
select = "$sea"
select_2nd = "$asphalt"
select_alt = "$nectarine"
accent = "$cherry_blossom"
accent_2nd = "$creamsicle"
accent_popup = "$nectarine"
accent_linenum = "$peach"
inactive = "$elephant"
focus = "$ink"
guide = "$soil"
guide_ruler = "$charcoal"
match = "$lemon"
error = "$salsa"
warning = "$lantern"
info = "$orchid"
hint = "fg"

[slots.debug]
active = "$cherry_blossom"
breakpoint = "$princess"
frameline = "$date"

[slots.mode]
normal = "$cherry_blossom"
normal_2nd = "$opium"
insert = "$sour_apple"
insert_2nd = "$sage"
select = "$sky"
select_2nd = "$cloud"

[slots.syntax]
variable = "$peach"
variable_builtin = "$princess"
variable_parameter = "$coral"
variable_member = "$cherry_blossom"
keyword = "$strawberry"
type = "$creamsicle"
type_variant = "syntax.constant"
function = "$lilac"
constant = "$sky"
label = "$goddess"
constructor = "syntax.label"
string = "$sour_apple"
attribute = "syntax.type"
namespace = "$sand"
tag = "syntax.namespace"
comment = "$elephant"
comment_doc = "fg"
operator = "syntax.punctuation"
punctuation = "$honeycomb"
punctuation_rainbow1 = "$honeycomb"
punctuation_rainbow2 = "$sand"
punctuation_rainbow3 = "$strawberry"
punctuation_rainbow4 = "$cherry_blossom"
punctuation_rainbow5 = "$lilac"
punctuation_rainbow6 = "$sky"
special = "$princess"
special_character = "syntax.special_string"
special_string = "$blueberry"
special_punctuation = "$strawberry"

[slots.diff]
plus = "$sour_apple"
minus = "$strawberry"
delta = "$sky"
delta_moved = "$peacock"
delta_conflict = "$sand"

[slots.markup]
heading = "$cherry_blossom"
heading_2nd = "$coral"
heading_3rd = "$sand"
heading_4th = "$creamsicle"
heading_5th = "$sour_apple"
heading_6th = "$goddess"
list = "$honeycomb"
list_checked = "$sour_apple"
list_unchecked = "$elephant"
link = "$peacock"
link_text = "$goddess"
bold = "$lilac"
italic = "$sky"
strikethrough = "fg"
quote = "$peach"
raw = "$sour_apple"

[slots.ansi]
black = "$raven"
black_bright = "$soil"
red = "$strawberry"
red_bright = "$sand"
green = "$sour_apple"
green_bright = "$goddess"
yellow = "$honeycomb"
yellow_bright = "$creamsicle"
blue = "$lilac"
blue_bright = "$blueberry"
magenta = "$cherry_blossom"
magenta_bright = "$princess"
cyan = "$sky"
cyan_bright = "$peacock"
white = "$elephant"
white_bright = "$chalk"
