author = "jezzy jumble"
license = "GPLv3"
blurb = "a comfy theme to keep you soft and warm."

[palette]
blackboard = "#181716"
strawberry = "#f56e7f"
sour_apple = "#bec975"
honeycomb = "#e8d6a7"
lilac = "#caa2ca"
cherry_blossom = "#e5a1a3"
sky = "#a5b6ce"
elephant = "#88847f"
soil = "#73665b"
salmon = "#f58669"
goddess = "#a2caa0"
creamsicle = "#f7bb6c"
blueberry = "#9293ec"
princess = "#ef7dc0"
peacock = "#5dccc3"
chalk = "#d5d0c9"
metal = "#212225"
date = "#210f11"
film = "#2e2a27"
charcoal = "#313735"
asphalt = "#43403d"
sea = "#0f3f4e"
opium = "#978182"
sage = "#878972"
cloud = "#808387"
nectarine = "#f1d090"
lemon = "#ffef43"

[slots]
bg = "$blackboard"
fg = "$chalk"
color0 = "bg"
color1 = "$strawberry"
color2 = "$sour_apple"
color3 = "$honeycomb"
color4 = "$lilac"
color5 = "$cherry_blossom"
color6 = "$sky"
color7 = "$elephant"
color8 = "$soil"
color9 = "$salmon"
color10 = "$goddess"
color11 = "$creamsicle"
color12 = "$blueberry"
color13 = "$princess"
color14 = "$peacock"
color15 = "$chalk"
select0 = "$sea"
select1 = "$onyx"
alt_select = "$nectarine"
alt_text = "bg"
comment = "$elephant"
link = "$peacock"
accent0 = "$cherry_blossom"
accent1 = "$creamsicle"
accent_text = "bg"
inactive = "$elephant"
inactive_text = "bg"
