[meta]
author = "jezzy jumble (@jezzy-ultra)"
license = "MPL-2.0"
blurb = "cute af theme for queers <3"

[palette]
cherry_blossom = "#eaa5a7"
strawberry = "#f76f80"
princess = "#fa7fb5"
lilac = "#caa2ca"
blueberry = "#9e9fec"
sky = "#a5b6ce"
peacock = "#8accc7"
goddess = "#a2caa0"
sour_apple = "#bec975"
lemon = "#ffef43"
honeycomb = "#f0e9ae"
nectar = "#f1d090"
creamsicle = "#f1c972"
peach = "#e6c1a4"
sand = "#f9a057"
coral = "#f7675c"
raven = "#0a0909"
ink = "#111010"
date = "#210f11"
blackboard = "#181716"
cocoa = "#1f1e1b"
film = "#2e2a27"
charcoal = "#313735"
sea = "#0f3f4e"
asphalt = "#433a31"
soil = "#584e46"
cloud = "#808387"
elephant = "#88847f"
opium = "#978182"
sage = "#878972"
olive = "#b1a585"
ash = "#b8b4ae"
chalk = "#d5d0c9"

[slots]
bg = "$blackboard"
# bg_alt
fg = "$chalk"
fg_alt = "$raven"
toolbar = "$film"
toolbar_popup = "$cocoa"
toolbar_alt = "$raven"
select = "$sea"
select_2nd = "$asphalt"
select_alt = "$nectar"
accent = "$cherry_blossom"
accent_2nd = "$creamsicle"
# accent_separator
accent_popup = "$nectar"
accent_linenum = "$peach"
inactive = "$elephant"
focus = "$ink"
guide = "$charcoal"
guide_inlay = "$soil"
guide_linenum = "$soil"
guide_ruler = "$charcoal"
guide_whitespace = "$soil"
match = "$lemon"
error = "$coral"
warning = "$nectar"
info = "$peacock"
hint = "fg"

[slots.debug]
active = "$princess"
breakpoint = "$coral"
frameline = "$date"

[slots.mode]
normal = "$cherry_blossom"
normal_2nd = "$opium"
insert = "$sour_apple"
insert_2nd = "$sage"
select = "$sky"
select_2nd = "$cloud"

[slots.syntax]
variable = "$cherry_blossom"
variable_builtin = "$princess"
variable_parameter = "$peach"
variable_member = "$cherry_blossom"
keyword = "$strawberry"
# keyword_operator
# keyword_function
# keyword_conditional
# keyword_repeat
# keyword_import
keyword_return = "$coral"
keyword_exception = "$coral"
# keyword_directive
# keyword_storage
type = "$creamsicle"
# type_builtin
type_variant = "syntax.constant"
function = "$lilac"
# function_builtin
# function_method
# function_macro
constant = "$sky"
# constant_builtin
# constant_boolean
# constant_number
# constant_character
label = "$goddess"
constructor = "syntax.label"
string = "$sour_apple"
attribute = "syntax.type"
namespace = "$sand"
tag = "syntax.namespace"
# tag_builtin
comment = "$elephant"
comment_doc = "$ash"
operator = "$honeycomb"
punctuation = "$olive"
punctuation_rainbow1 = "$goddess"
punctuation_rainbow2 = "$sky"
punctuation_rainbow3 = "$lilac"
punctuation_rainbow4 = "$cherry_blossom"
punctuation_rainbow5 = "$sand"
punctuation_rainbow6 = "$creamsicle"
special = "$princess"
# special_function
special_character = "syntax.special_string"
special_string = "$blueberry"
special_punctuation = "$strawberry"
# rainbow = [[[[[[]]]]]]

[slots.diff]
plus = "$sour_apple"
minus = "$strawberry"
delta = "$sky"
delta_moved = "$peacock"
delta_conflict = "$sand"

[slots.markup]
heading = "$cherry_blossom"
heading_2nd = "$strawberry"
heading_3rd = "$sand"
heading_4th = "$creamsicle"
heading_5th = "$sour_apple"
heading_6th = "$goddess"
list = "$honeycomb"
list_checked = "$sour_apple"
list_unchecked = "$elephant"
link = "$peacock"
link_text = "$goddess"
bold = "$lilac"
italic = "$sky"
strikethrough = "$ash"
quote = "$peach"
raw = "$sour_apple"

[slots.ansi]
black = "$raven"
black_bright = "$soil"
red = "$strawberry"
red_bright = "$sand"
green = "$sour_apple"
green_bright = "$goddess"
yellow = "$honeycomb"
yellow_bright = "$creamsicle"
blue = "$lilac"
blue_bright = "$blueberry"
magenta = "$cherry_blossom"
magenta_bright = "$princess"
cyan = "$sky"
cyan_bright = "$peacock"
white = "$elephant"
white_bright = "$ash"
