[meta]
author = "jezzy jumble (@jezzy-ultra)"
license = "MPL-2.0"
blurb = "cute af theme for queers ♡"
upstream = "https://github.com/cutiepro"
upstream_template = "{base}/{port}/blob/main/{path}"  # default: `{base}/{port}/blob/main/{path}`

[palette]
blackboard = "#181716"
strawberry = "#f56e7f"
sour_apple = "#bec975"
honeycomb = "#e8d6a7"
lilac = "#caa2ca"
cherry_blossom = "#e5a1a3"
sky = "#a5b6ce"
elephant = "#88847f"
soil = "#73665b"
sand = "#f98964"
goddess = "#a2caa0"
creamsicle = "#f7bb6c"
blueberry = "#9e9fec"
princess = "#fa7fb5"
peacock = "#8accc7"
chalk = "#d5d0c9"
peach = "#e3bea3"
coral = "#f5968c"
raven = "#0a0909"
ink = "#111010"
cocoa = "#1f1e1b"
date = "#210f11"
film = "#2e2a27"
charcoal = "#313735"
asphalt = "#433a31"
sea = "#0f3f4e"
opium = "#978182"
sage = "#878972"
cloud = "#808387"
nectarine = "#f1d090"
lemon = "#ffef43"

[slots]
bg = "$blackboard"
alt_bg = "bg"
fg = "$chalk"
alt_fg = "$raven"
toolbar = "$film"
toolbar_popup = "$cocoa"  # default: `toolbar`
alt_toolbar = "$raven"
select = "$sea"
select_2nd = "$asphalt"  # default: `select`
alt_select = "$nectarine"
accent = "$cherry_blossom"
accent_2nd = "$creamsicle"  # default: `accent`
accent_separator = "accent"  # default: `accent`
accent_popup = "$nectarine"  # default: `accent`
accent_linenum = "$peach"  # default: `accent`
inactive = "$elephant"
focus = "$ink"
guide = "$soil"
guide_inlay = "$soil"  # default: `guide`
guide_linenum = "$soil"  # default: `guide`
guide_ruler = "$charcoal"  # default: `guide`
guide_whitespace = "$soil"  # default: `guide`
match = "$lemon"
error = "$strawberry"
warning = "$creamsicle"
hint = "$lilac"
info = "fg"
unnecessary = "$honeycomb"

[slots.debug]
active = "$cherry_blossom"
breakpoint = "$princess"
frameline = "$date"

[slots.mode]
normal = "$cherry_blossom"
normal_2nd = "$opium"  # default: `mode.normal`
insert = "$sour_apple"
insert_2nd = "$sage"  # default: `mode.insert`
select = "$sky"
select_2nd = "$cloud"  # default: `mode.select`

[slots.syntax]
variable = "$peach"
variable_builtin = "$princess"  # default: `syntax.variable`
variable_parameter = "$coral"  # default: `syntax.variable`
variable_member = "$cherry_blossom"  # default: `syntax.variable`
keyword = "$strawberry"
keyword_operator = "syntax.keyword"  # default: `syntax.keyword`
keyword_function = "syntax.keyword"  # default: `syntax.keyword`
keyword_conditional = "syntax.keyword"  # default: `syntax.keyword`
keyword_repeat = "syntax.keyword"  # default: `syntax.keyword`
keyword_import = "syntax.keyword"  # default: `syntax.keyword`
keyword_return = "syntax.keyword"  # default: `syntax.keyword`
keyword_exception = "syntax.keyword"  # default: `syntax.keyword`
keyword_directive = "syntax.keyword"  # default: `syntax.keyword`
keyword_storage = "syntax.keyword"  # default: `syntax.keyword`
type = "$creamsicle"
type_builtin = "syntax.type"  # default: `syntax.type`
type_variant = "syntax.constant"  # default: `syntax.type`
function = "$lilac"
function_builtin = "syntax.function"  # default: `syntax.function`
function_method = "syntax.function"  # default: `syntax.function`
function_macro = "syntax.function"  # default: `syntax.function`
constant = "$sky"
constant_builtin = "syntax.constant"  # default: `syntax.constant`
constant_boolean = "syntax.constant"  # default: `syntax.constant`
constant_number = "syntax.constant"  # default: `syntax.constant`
constant_character = "syntax.string"  # default: `syntax.constant`
label = "$goddess"
constructor = "syntax.label"
string = "$sour_apple"
attribute = "syntax.type"
namespace = "$sand"
tag = "syntax.namespace"
tag_builtin = "syntax.tag"  # default: `syntax.tag`
comment = "$elephant"
operator = "syntax.punctuation"
punctuation = "$honeycomb"
punctuation_rainbow1 = "$honeycomb"  # default: `syntax.punctuation`
punctuation_rainbow2 = "$sand"  # default: `syntax.punctuation`
punctuation_rainbow3 = "$strawberry"  # default: `syntax.punctuation`
punctuation_rainbow4 = "$cherry_blossom"  # default: `syntax.punctuation`
punctuation_rainbow5 = "$lilac"  # default: `syntax.punctuation`
punctuation_rainbow6 = "$sky"  # default: `syntax.punctuation`
special = "$princess"
special_function = "syntax.function"  # default: `syntax.special`
special_character = "syntax.special_string"  # default: `syntax.special`
special_string = "$blueberry"  # default: `syntax.special`
special_punctuation = "$strawberry"  # default: `syntax.special`

[slots.diff]
plus = "$sour_apple"
minus = "$strawberry"
delta = "$sky"
delta_moved = "$peacock"  # default: `diff.delta`
delta_conflict = "$sand"  # default: `diff.delta`

[slots.markup]
heading = "$cherry_blossom"
heading_2nd = "$coral"  # default: `markup.heading`
heading_3rd = "$sand"  # default: `markup.heading`
heading_4th = "$creamsicle"  # default: `markup.heading`
heading_5th = "$sour_apple"  # default: `markup.heading`
heading_6th = "$goddess"  # default: `markup.heading`
list = "$honeycomb"
list_numbered = "markup.list"  # default: `markup.list`
list_checked = "$sour_apple"  # default: `markup.list`
list_unchecked = "$elephant"  # default: `markup.list`
link = "$peacock"
link_text = "$goddess"
bold = "$lilac"
italic = "$sky"
strikethrough = "fg"
quote = "$peach"
raw = "$sour_apple"

[slots.ansi]
black = "$raven"
black_bright = "$soil"  # default: `ansi.black`
red = "$strawberry"
red_bright = "$sand"  # default: `ansi.red`
green = "$sour_apple"
green_bright = "$goddess"  # default: `ansi.green`
yellow = "$honeycomb"
yellow_bright = "$creamsicle"  # default: `ansi.yellow`
blue = "$lilac"
blue_bright = "$blueberry"  # default: `ansi.blue`
magenta = "$cherry_blossom"
magenta_bright = "$princess"  # default: `ansi.magenta`
cyan = "$sky"
cyan_bright = "$peacock"  # default: `ansi.cyan`
white = "$elephant"
white_bright = "$chalk"  # default: `ansi.white`
